export const GET_LIST_PRODUCTS = "GET_LIST_PRODUCTS";
export const GET_LIST_PRODUCTS_SUCCESS = "GET_LIST_PRODUCTS_SUCCESS";
export const GET_LIST_PRODUCTS_ERROR = "GET_LIST_PRODUCTS_ERROR";
export const GET_LIST_PRODUCTS_CLEAR = "GET_LIST_PRODUCTS_CLEAR";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_CLEAR = "GET_PRODUCT_CLEAR";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_ERROR";
